# Generated by Django 5.0 on 2023-12-27 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('shows', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('movie_poster', models.ImageField(default='images/unkonwn2.jpg', upload_to='images/')),
                ('cast', models.TextField()),
                ('genre', models.CharField(choices=[('Action', 'AC'), ('Comedy', 'CO'), ('Fantasy', 'FA'), ('Horror', 'HO'), ('Mystery', 'MY'), ('Romance', 'RO'), ('Thriller', 'TH'), ('Mystery', 'MY'), ('Romance', 'RO'), ('Thriller', 'TH'), ('Unknown', 'Un')], default='Unknown', max_length=20)),
                ('language', models.CharField(choices=[('Arabic', 'Ar'), ('English', 'En'), ('French', 'Fr'), ('Chinese', 'Ch'), ('Korean', 'Ko'), ('Hindi', 'Hi')], default='Arabic', max_length=15)),
                ('country', models.CharField(choices=[('Egypt', 'Eg'), ('United-states', 'US'), ('United Kingdom', 'UK'), ('India', 'In'), ('Korea', 'Ko'), ('China', 'Ch')], default='Egypt', max_length=20)),
                ('duration', models.DurationField(max_length=15)),
                ('experience', models.CharField(max_length=15)),
                ('threeD', models.BooleanField()),
                ('releaseYear', models.DateField()),
                ('trailer', models.URLField()),
                ('description', models.TextField()),
                ('showtimes', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movie_show', to='Cinema.showtime')),
            ],
        ),
    ]
