# Generated by Django 5.0 on 2023-12-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cinema', '0003_remove_showtime_movie_showtimes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='movie_showtimes',
            field=models.ManyToManyField(related_name='movie_show', to='Cinema.movie'),
        ),
    ]
