# Generated by Django 5.0 on 2023-12-28 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cinema', '0006_seat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='seatnID',
            new_name='useat',
        ),
    ]
