# Generated by Django 5.0 on 2023-12-28 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cinema', '0007_rename_seatnid_seat_useat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='seat',
        ),
    ]
