# Generated by Django 5.0 on 2023-12-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cinema', '0008_delete_seat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('seat', models.AutoField(primary_key=True, serialize=False)),
                ('seatno', models.CharField(max_length=10)),
            ],
        ),
    ]
