# Generated by Django 5.0 on 2023-12-28 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cinema', '0009_seat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='seat',
            new_name='seats',
        ),
    ]
