# Generated by Django 5.0 on 2023-12-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cinema', '0010_rename_seat_seat_seats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment', models.AutoField(primary_key=True, serialize=False)),
                ('cardname', models.CharField(max_length=20)),
                ('cardno', models.CharField(max_length=16)),
                ('expmonth', models.CharField(max_length=10)),
                ('expyear', models.CharField(max_length=4)),
                ('cvv', models.CharField(max_length=3)),
            ],
        ),
    ]
